### ISSUE TITLE
Four builds triggered for every commit to PR/branch

### ISSUE THREAD

**Issue by mi-yu** [CovEducation/CovEducation#12]
Would be good to not run 4 of the same build!

**Comment by oupadhyay** [comment]
Yup! Just the Travis CI - Pull Request, would be good. It does both phases: test (the branch) and publish (once merged).

**Comment by mi-yu** [comment]
fixed by disabling repo builds on travis-ci.org which is actually separate from the builds triggered from travis-ci.com!
